# Atlas OS — Morning Report Workflow
# Runs daily at 07:00 Israel time, collects signals, outputs Markdown report

name: atlas-morning-report

on:
  schedule:
    - cron: '0 4 * * 1-5'  # 04:00 UTC = 07:00 Israel (summer time)
  workflow_dispatch:

permissions:
  issues: write
  contents: read
  actions: read
  pull-requests: read

jobs:
  morning-report:
    name: Generate Morning Report
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect signals
        env:
          GH_TOKEN: ${{ secrets.ATLAS_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "# Atlas Daily Signal — $(date +%Y-%m-%d)" > report.md
          echo "" >> report.md

          echo "## Recent Commits" >> report.md
          gh api repos/$REPO/commits --jq '.[0:10] | .[] | "- \(.commit.message | split("\n")[0]) (\(.sha[0:7]))"' >> report.md 2>/dev/null || echo "- None" >> report.md
          echo "" >> report.md

          echo "## Open PRs" >> report.md
          gh pr list --repo $REPO --state open --json number,title,headRefName --jq '.[] | "- #\(.number): \(.title) (\(.headRefName))"' >> report.md 2>/dev/null || echo "- None" >> report.md
          echo "" >> report.md

          echo "## Open Issues" >> report.md
          gh issue list --repo $REPO --state open --limit 20 --json number,title,labels --jq '.[] | "- #\(.number): \(.title) [\(.labels | map(.name) | join(", "))]"' >> report.md 2>/dev/null || echo "- None" >> report.md
          echo "" >> report.md

          echo "## CI Status (last 5 runs)" >> report.md
          gh run list --repo $REPO --limit 5 --json name,status,conclusion,createdAt --jq '.[] | "- \(.name): \(.conclusion // .status) (\(.createdAt))"' >> report.md 2>/dev/null || echo "- No runs" >> report.md
          echo "" >> report.md

          FAILURES=$(gh run list --repo $REPO --limit 5 --json conclusion --jq '[.[] | select(.conclusion == "failure")] | length')
          if [ "$FAILURES" -gt "0" ]; then
            echo "## ⚠️ FAILURES: $FAILURES failed runs in last 5" >> report.md
          fi
          echo "---" >> report.md
          echo "*Generated by Atlas OS at $(date -u +%Y-%m-%dT%H:%M:%SZ)*" >> report.md

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: morning-report-${{ github.run_number }}
          path: report.md
          retention-days: 30

      - name: Create or update daily report issue
        env:
          GH_TOKEN: ${{ secrets.ATLAS_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          TITLE="Atlas Daily Signal — $(date +%Y-%m-%d)"
          BODY=$(cat report.md)
          EXISTING=$(gh issue list --repo $REPO --search "\"$TITLE\" in:title" --state open --json number --jq '.[0].number' 2>/dev/null)
          if [ -n "$EXISTING" ] && [ "$EXISTING" != "null" ]; then
            gh issue comment $EXISTING --repo $REPO --body "$BODY"
          else
            gh issue create --repo $REPO --title "$TITLE" --body "$BODY" --label "atlas"
          fi
