"""init

Revision ID: 110c4a1fad56
Revises: 
Create Date: 2026-02-03 18:15:39.721521
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '110c4a1fad56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_provider'), 'api_usage', ['provider'], unique=False)
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_runs_automation_name'), 'automation_runs', ['automation_name'], unique=False)
    op.create_index(op.f('ix_automation_runs_status'), 'automation_runs', ['status'], unique=False)
    op.create_table('lead_enrichment_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_run_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enriched_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['automation_run_id'], ['automation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_enrichment_jobs_email'), 'lead_enrichment_jobs', ['email'], unique=False)
    op.create_index('ix_lead_enrichment_jobs_email_status', 'lead_enrichment_jobs', ['email', 'status'], unique=False)
    op.create_index(op.f('ix_lead_enrichment_jobs_status'), 'lead_enrichment_jobs', ['status'], unique=False)
    op.create_table('pipeline_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_run_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('rows_extracted', sa.Integer(), nullable=True),
    sa.Column('rows_loaded', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['automation_run_id'], ['automation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_executions_status'), 'pipeline_executions', ['status'], unique=False)
    op.create_table('social_media_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_run_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['automation_run_id'], ['automation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_posts_status'), 'social_media_posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_media_posts_status'), table_name='social_media_posts')
    op.drop_table('social_media_posts')
    op.drop_index(op.f('ix_pipeline_executions_status'), table_name='pipeline_executions')
    op.drop_table('pipeline_executions')
    op.drop_index(op.f('ix_lead_enrichment_jobs_status'), table_name='lead_enrichment_jobs')
    op.drop_index('ix_lead_enrichment_jobs_email_status', table_name='lead_enrichment_jobs')
    op.drop_index(op.f('ix_lead_enrichment_jobs_email'), table_name='lead_enrichment_jobs')
    op.drop_table('lead_enrichment_jobs')
    op.drop_index(op.f('ix_automation_runs_status'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_automation_name'), table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_api_usage_provider'), table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
